import type { Metadata } from "next";
import { ShieldCheck } from "lucide-react";
import { LegalDocument, type LegalSection } from "@/features/marketing/LegalDocument/LegalDocument";

export const metadata: Metadata={title:"Privacy Policy | Sauti",description:"How Sauti collects, uses, protects, and gives you control over personal and Google user data."};
const sections:LegalSection[]=[
{id:"scope",title:"Who this policy covers",paragraphs:["This Privacy Policy explains how Sauti processes information when businesses create AI voice agents, connect communication and productivity services, receive calls, manage bookings, and review conversation analytics. A business using Sauti controls the caller and customer information processed in its workspace; Sauti processes that information to provide the platform."]},
{id:"collect",title:"Information we collect",paragraphs:["We collect information supplied by workspace owners, users, callers, connected providers, and the devices used to access Sauti."],bullets:["Account and workspace information, including names, business details, email addresses, authentication records, plan and usage information.","Agent configuration, knowledge content, prompts, business hours, routing rules, enabled tools, and integration preferences.","Call and message data, including phone numbers, audio where recording is enabled, transcripts, events, duration, language, summaries, sentiment, booking details, and information a caller chooses to provide.","Technical and security data, including IP address, browser, device, timestamps, request logs, OAuth state, and security events.","Integration data returned by providers that a workspace explicitly connects."]},
{id:"google",title:"Google user data",paragraphs:["When a workspace connects Google Calendar, Sauti may read calendar identity, calendar lists, availability or free/busy information, and event details needed to check availability, create, update, or cancel appointments at the user's direction. When Google Sheets is connected, Sauti may read configured spreadsheet metadata or rows for enabled agent tools and append configured post-call fields such as date, caller, duration, outcome, summary, and booking details.","Sauti uses Google user data only to provide and improve the user-facing integration features the workspace enables. Sauti does not sell Google user data, use it for advertising, use it to train generalized AI or machine-learning models, or allow humans to read it except when necessary for security, support requested by the user, legal compliance, or service operation. Sauti's use and transfer of information received from Google APIs adheres to the Google API Services User Data Policy, including the Limited Use requirements."],bullets:["OAuth access and refresh tokens are encrypted at rest and are not exposed in ordinary API responses.","Access is tenant-scoped and limited to the connected workspace and agents it enables.","Disconnecting an integration stops new Google API access and removes or invalidates stored connection credentials as supported by the provider.","Users can also revoke Sauti from their Google Account permissions page."]},
{id:"use",title:"How information is used",bullets:["Authenticate users, operate workspaces, meter usage, and provide support.","Transcribe and synthesize speech, generate responses, route calls, answer configured questions, and perform enabled tools.","Create and manage bookings, send confirmations, synchronize selected integrations, and run configured post-call workflows.","Provide transcripts, recordings where enabled, summaries, analytics, quality monitoring, fraud prevention, and reliability.","Meet legal obligations, enforce platform terms, and protect users, callers, Sauti, and the public."]},
{id:"sharing",title:"Service providers and sharing",paragraphs:["Sauti shares information only as needed to operate requested features, comply with law, protect rights and safety, or complete a business transaction subject to appropriate safeguards. Depending on configuration, processors may include hosting and database providers, speech recognition, language-model and text-to-speech providers, telephony and messaging providers, email delivery, authentication, monitoring, payment services, and integrations selected by the workspace such as Google, Calendly, HubSpot, Salesforce, Slack, or webhooks.","Workspace owners are responsible for telling callers about their use of AI, recording, and connected systems where law requires it. Sauti does not sell personal information."]},
{id:"retention",title:"Retention, controls, and deletion",paragraphs:["We retain information for as long as needed to provide the service, satisfy workspace configuration and contractual needs, maintain security and audit records, resolve disputes, and meet legal obligations. Call recordings are retained only when recording is enabled; transcripts, summaries, bookings, and delivery records may remain until the workspace deletes them or its account, subject to backups and legal requirements.","To request access, correction, export, restriction, or deletion, contact the workspace that collected your caller information or email Sauti. A workspace can disconnect integrations and delete agents and related configuration through available product controls. Verified requests are handled according to applicable law."]},
{id:"security",title:"Security and international processing",paragraphs:["Sauti uses administrative, technical, and organizational safeguards including tenant-scoped authorization, encrypted provider credentials, HTTPS, access controls, logging, backups, and secret-management practices. No system can guarantee absolute security. Information may be processed in countries where Sauti or its providers operate, with safeguards appropriate to the data and applicable law."]},
{id:"sensitive",title:"Children and sensitive information",paragraphs:["Sauti is a business service and is not directed to children. Workspaces should not configure agents to collect unnecessary sensitive information. Health, financial, identity, or other sensitive data should be collected only with a lawful purpose, appropriate notice, and safeguards. Payment actions require confirmation and should use approved payment providers rather than collecting full payment credentials in conversation."]},
{id:"changes",title:"Changes and contact",paragraphs:["We may update this policy as Sauti and applicable requirements evolve. Material changes will be identified by a new effective date and, where appropriate, an in-product or email notice. Questions and privacy requests can be sent to support@sauti.uk. Please identify the relevant workspace or call when possible, without emailing passwords, OAuth tokens, or other secrets."]}
];
export default function PrivacyPage(){return <LegalDocument eyebrow="Trust center" title="Privacy, in plain language" summary="How Sauti handles workspace, conversation, booking, and connected-service data—and the controls available to you." effectiveDate="12 July 2026" icon={ShieldCheck} highlights={["Google data is used only for features you enable","OAuth credentials are encrypted and tenant-scoped","Sauti does not sell personal or Google user data"]} sections={sections}/>}
