ALTER TABLE agents ADD COLUMN description VARCHAR(500);
ALTER TABLE agents ADD COLUMN max_call_duration_seconds INT NOT NULL DEFAULT 300;
ALTER TABLE agents ADD COLUMN save_transcript BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE agents ADD COLUMN record_calls BOOLEAN NOT NULL DEFAULT FALSE;
