#!/usr/bin/env bash
set -Eeuo pipefail

cd /opt/sauti

source_file="${1:-.env.external-source}"
target_file="${2:-.env.production}"

if [[ ! -f "${source_file}" ]]; then
  echo "${source_file} not found"
  exit 1
fi

if [[ ! -f "${target_file}" ]]; then
  echo "${target_file} not found"
  exit 1
fi

python3 - "${source_file}" "${target_file}" <<'PY'
import sys
from pathlib import Path
from urllib.parse import parse_qsl, quote, unquote, urlsplit

source_path = Path(sys.argv[1])
target_path = Path(sys.argv[2])

managed = {
    "NEON_DATABASE_URL",
    "NEON_POOLED_DATABASE_URL",
    "DB_URL",
    "DB_USER",
    "DB_PASSWORD",
    "SPRING_FLYWAY_URL",
    "SPRING_FLYWAY_USER",
    "SPRING_FLYWAY_PASSWORD",
    "SPRING_REDIS_HOST",
    "SPRING_REDIS_PORT",
    "SPRING_REDIS_PASSWORD",
    "SPRING_REDIS_SSL_ENABLED",
    "SPRING_MAIL_HOST",
    "SPRING_MAIL_PORT",
    "SPRING_MAIL_USERNAME",
    "SPRING_MAIL_PASSWORD",
    "SPRING_MAIL_SMTP_AUTH",
    "SPRING_MAIL_SMTP_STARTTLS_ENABLE",
    "SPRING_MAIL_SMTP_SSL_ENABLE",
    "EMAIL_FROM",
    "EMAIL_REPLY_TO",
}


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        values[key] = value
    return values


def require(values: dict[str, str], key: str) -> str:
    value = values.get(key, "").strip()
    if not value:
        raise SystemExit(f"{key} is required in {source_path}")
    return value


def jdbc_url(raw_url: str) -> str:
    parsed = urlsplit(raw_url)
    if parsed.scheme not in {"postgres", "postgresql"}:
        raise SystemExit(f"Unsupported Postgres URL scheme: {parsed.scheme}")
    host = parsed.hostname or ""
    if not host:
        raise SystemExit("Postgres URL host is required")
    netloc = host
    if parsed.port:
        netloc += f":{parsed.port}"
    query = parsed.query
    return f"jdbc:postgresql://{netloc}{parsed.path}" + (f"?{query}" if query else "")


def pg_user_password(raw_url: str) -> tuple[str, str]:
    parsed = urlsplit(raw_url)
    return unquote(parsed.username or ""), unquote(parsed.password or "")


def dotenv_value(value: str) -> str:
    if value == "":
        return ""
    safe = all(ch.isalnum() or ch in "._-/:@?=&%+" for ch in value)
    if safe:
        return value
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


source = read_env(source_path)
target_lines = target_path.read_text().splitlines()

direct = require(source, "NEON_DATABASE_URL")
pooled = require(source, "NEON_POOLED_DATABASE_URL")
db_user, db_password = pg_user_password(pooled)
flyway_user, flyway_password = pg_user_password(direct)
if not db_user or not db_password:
    raise SystemExit("NEON_POOLED_DATABASE_URL must include user and password")
if not flyway_user or not flyway_password:
    raise SystemExit("NEON_DATABASE_URL must include user and password")

updates = {
    "NEON_DATABASE_URL": direct,
    "NEON_POOLED_DATABASE_URL": pooled,
    "DB_URL": jdbc_url(pooled),
    "DB_USER": db_user,
    "DB_PASSWORD": db_password,
    "SPRING_FLYWAY_URL": jdbc_url(direct),
    "SPRING_FLYWAY_USER": flyway_user,
    "SPRING_FLYWAY_PASSWORD": flyway_password,
    "SPRING_REDIS_HOST": require(source, "UPSTASH_REDIS_HOST"),
    "SPRING_REDIS_PORT": source.get("UPSTASH_REDIS_PORT", "6379").strip() or "6379",
    "SPRING_REDIS_PASSWORD": require(source, "UPSTASH_REDIS_PASSWORD"),
    "SPRING_REDIS_SSL_ENABLED": "true",
    "SPRING_MAIL_HOST": "smtp.resend.com",
    "SPRING_MAIL_PORT": "587",
    "SPRING_MAIL_USERNAME": "resend",
    "SPRING_MAIL_PASSWORD": require(source, "RESEND_API_KEY"),
    "SPRING_MAIL_SMTP_AUTH": "true",
    "SPRING_MAIL_SMTP_STARTTLS_ENABLE": "true",
    "SPRING_MAIL_SMTP_SSL_ENABLE": "false",
    "EMAIL_FROM": require(source, "EMAIL_FROM"),
    "EMAIL_REPLY_TO": source.get("EMAIL_REPLY_TO", source["EMAIL_FROM"]).strip() or source["EMAIL_FROM"],
}

kept_lines = []
for line in target_lines:
    stripped = line.strip()
    if "=" in stripped and not stripped.startswith("#"):
        key = stripped.split("=", 1)[0].strip()
        if key in managed:
            continue
    kept_lines.append(line)

block = [
    "",
    "# External managed services. Generated by deploy/configure-external-services-env.sh.",
]
block.extend(f"{key}={dotenv_value(value)}" for key, value in updates.items())

target_path.write_text("\n".join(kept_lines + block).rstrip() + "\n")
PY

chmod 600 "${target_file}"
echo "Updated ${target_file} for Neon, Upstash, and Resend."
