package com.sauti.agent;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Size;
import jakarta.validation.constraints.Email;
import java.util.List;
import java.util.Map;
import java.util.UUID;

public final class AgentDtos {
    private AgentDtos() {
    }

    public record AgentRequest(
            @NotBlank String name,
            @Size(max = 500) String description,
            @NotBlank String greetingMessage,
            @NotBlank String systemPrompt,
            @NotBlank String defaultLanguage,
            @NotEmpty List<String> supportedLanguages,
            String ttsVoiceId,
            String humanTransferNumber,
            List<String> escalationPhrases,
            boolean bookingEnabled,
            String timezone,
            @Size(max = 10000) String knowledgeBase,
            String operatingHours,
            String afterHoursBehavior,
            @Size(max = 1000) String afterHoursMessage,
            Integer maxCallDurationSeconds,
            Boolean saveTranscript,
            Boolean recordCalls,
            String llmTier,
            Double bargeInSensitivity,
            Integer bargeInGraceMs,
            Integer endCallOnSilenceSeconds,
            Integer reminderAfterSilenceSeconds,
            Integer maxReminders,
            Boolean detectVoicemail,
            Boolean handleCallScreening,
            Boolean dtmfEnabled,
            Integer sttEndpointingMs,
            String sttVocabularyDomain,
            String sttBoostedKeywords,
            List<String> safetyGuardrails,
            List<String> postCallExtractionFields,
            List<String> bookingRequiredFields,
            List<String> bookingNotificationChannels,
            @Email @Size(max = 320) String bookingNotificationRecipient,
            String dtmfTerminationKey,
            Integer dtmfInputTimeoutSeconds,
            Integer dtmfMaxDigits,
            Map<String, String> dtmfDigitMappings,
            Boolean webVoiceEnabled,
            List<String> webVoiceAllowedOrigins,
            Boolean webVoiceRequireConsent,
            Boolean whatsappEnabled,
            String whatsappPhoneNumberId
    ) {
    }

    public record AgentTimezoneRequest(@NotBlank @Size(max = 100) String timezone) {
    }

    public record AgentResponse(
            UUID id,
            String name,
            String description,
            String twilioPhoneNumber,
            String twilioPhoneNumberSid,
            String phoneNumberProvider,
            String phoneNumberStatus,
            String phoneNumberOrderId,
            java.time.OffsetDateTime phoneNumberAssignedAt,
            String defaultLanguage,
            List<String> supportedLanguages,
            String greetingMessage,
            String systemPrompt,
            String ttsVoiceId,
            String humanTransferNumber,
            List<String> escalationPhrases,
            boolean bookingEnabled,
            String timezone,
            String knowledgeBase,
            String operatingHours,
            String afterHoursBehavior,
            String afterHoursMessage,
            int maxCallDurationSeconds,
            boolean saveTranscript,
            boolean recordCalls,
            String llmTier,
            double bargeInSensitivity,
            int bargeInGraceMs,
            int endCallOnSilenceSeconds,
            int reminderAfterSilenceSeconds,
            int maxReminders,
            boolean detectVoicemail,
            boolean handleCallScreening,
            boolean dtmfEnabled,
            String dtmfTerminationKey,
            int dtmfInputTimeoutSeconds,
            int dtmfMaxDigits,
            Map<String, String> dtmfDigitMappings,
            int sttEndpointingMs,
            String sttVocabularyDomain,
            String sttBoostedKeywords,
            List<String> safetyGuardrails,
            List<String> postCallExtractionFields,
            List<String> bookingRequiredFields,
            List<String> bookingNotificationChannels,
            String bookingNotificationRecipient,
            String businessType,
            String primaryUseCase,
            String businessWebsite,
            List<String> bookableServices,
            String calendarProvider,
            String routingPolicy,
            String voiceProfile,
            boolean webVoiceEnabled,
            String webVoicePublicId,
            List<String> webVoiceAllowedOrigins,
            boolean webVoiceRequireConsent,
            boolean whatsappEnabled,
            String whatsappPhoneNumberId,
            boolean active
    ) {
        public static AgentResponse from(Agent agent) {
            return new AgentResponse(
                    agent.getId(),
                    agent.getName(),
                    agent.getDescription(),
                    agent.getTwilioPhoneNumber(),
                    agent.getTwilioPhoneNumberSid(),
                    agent.getPhoneNumberProvider(),
                    agent.getPhoneNumberStatus(),
                    agent.getPhoneNumberOrderId(),
                    agent.getPhoneNumberAssignedAt(),
                    agent.getDefaultLanguage(),
                    agent.getSupportedLanguages(),
                    agent.getGreetingMessage(),
                    agent.getSystemPrompt(),
                    agent.getTtsVoiceId(),
                    agent.getHumanTransferNumber(),
                    agent.getEscalationPhrases(),
                    agent.isBookingEnabled(),
                    agent.getTimezone(),
                    agent.getKnowledgeBase(),
                    agent.getOperatingHours(),
                    agent.getAfterHoursBehavior(),
                    agent.getAfterHoursMessage(),
                    agent.getMaxCallDurationSeconds(),
                    agent.isSaveTranscript(),
                    agent.isRecordCalls(),
                    agent.getLlmTier(),
                    agent.getBargeInSensitivity(),
                    agent.getBargeInGraceMs(),
                    agent.getEndCallOnSilenceSeconds(),
                    agent.getReminderAfterSilenceSeconds(),
                    agent.getMaxReminders(),
                    agent.isDetectVoicemail(),
                    agent.isHandleCallScreening(),
                    agent.isDtmfEnabled(),
                    agent.getDtmfTerminationKey(),
                    agent.getDtmfInputTimeoutSeconds(),
                    agent.getDtmfMaxDigits(),
                    agent.getDtmfDigitMappings(),
                    agent.getSttEndpointingMs(),
                    agent.getSttVocabularyDomain(),
                    agent.getSttBoostedKeywords(),
                    agent.getSafetyGuardrails(),
                    agent.getPostCallExtractionFields(),
                    agent.getBookingRequiredFields(),
                    agent.getBookingNotificationChannels(),
                    agent.getBookingNotificationRecipient(),
                    agent.getBusinessType(),
                    agent.getPrimaryUseCase(),
                    agent.getBusinessWebsite(),
                    agent.getBookableServices(),
                    agent.getCalendarProvider(),
                    agent.getRoutingPolicy(),
                    agent.getVoiceProfile(),
                    agent.isWebVoiceEnabled(),
                    agent.getWebVoicePublicId(),
                    agent.getWebVoiceAllowedOrigins(),
                    agent.isWebVoiceRequireConsent(),
                    agent.isWhatsappEnabled(),
                    agent.getWhatsappPhoneNumberId(),
                    agent.isActive()
            );
        }
    }

    public record AgentStatsResponse(UUID agentId, long totalCalls, long bookingCalls, double bookingRate) {
    }
}
