import type { Metadata } from "next";
import { ScrollText } from "lucide-react";
import { LegalDocument, type LegalSection } from "@/features/marketing/LegalDocument/LegalDocument";

export const metadata:Metadata={title:"Terms of Service | Sauti",description:"Terms governing access to and use of the Sauti AI voice-agent platform."};
const sections:LegalSection[]=[
{id:"agreement",title:"Agreement and eligibility",paragraphs:["These Terms govern access to Sauti's AI voice-agent platform, dashboard, APIs, web voice, phone channels, booking tools, analytics, and integrations. By creating a workspace, connecting a provider, or using the service, you agree to these Terms on behalf of yourself and, where applicable, your organization. You must have legal capacity and authority to accept them."]},
{id:"service",title:"The Sauti service",paragraphs:["Sauti lets organizations configure multilingual AI agents to answer or place supported calls, handle inquiries, qualify leads, collect configured information, schedule appointments, invoke approved tools, and create post-call records. Features and provider availability may differ by plan, geography, language, channel, or integration."],bullets:["AI responses, transcripts, summaries, sentiment, extracted details, and speech recognition may contain errors and must be checked before consequential use.","Sauti is not an emergency service and does not provide medical, legal, financial, or other professional advice.","Preview, test, beta, or third-party-dependent features may change or become unavailable."]},
{id:"accounts",title:"Accounts and workspace responsibility",paragraphs:["You are responsible for accurate registration information, authorized workspace users, secure credentials, activity performed through your account, and promptly reporting suspected compromise. Each workspace must use Sauti only for organizations and data it is authorized to represent and process."],bullets:["Configure agents, prompts, knowledge, tools, business hours, escalation routes, and integration permissions accurately.","Review agent performance and maintain a suitable human fallback for urgent, sensitive, or high-impact situations.","Do not place secrets in prompts, public knowledge, transcripts, or support messages."]},
{id:"calls",title:"Calls, consent, and customer communications",paragraphs:["You are responsible for the legality and content of calls and messages initiated or received through your agents. This includes obtaining consent and giving notices required for automated calls, AI interaction, call recording, transcription, marketing, and messaging in every applicable jurisdiction."],bullets:["Use accurate caller identification and honor opt-out, do-not-call, quiet-hour, and suppression requirements.","Do not impersonate a person or organization, mislead callers about material facts, or conceal AI use where disclosure is required.","Do not use Sauti for emergency dispatch, unlawful surveillance, harassment, fraud, discrimination, or deceptive high-pressure practices."]},
{id:"data",title:"Customer data and connected services",paragraphs:["You retain responsibility for data submitted to your workspace and grant Sauti the limited rights needed to host, process, transmit, and transform it to provide, secure, support, and improve the service. You confirm that you have a lawful basis and necessary permissions for that processing.","When you connect Google Calendar, Google Sheets, a CRM, messaging service, webhook, or another provider, you instruct Sauti to exchange the data needed for the features you enable. Your use of each provider remains subject to that provider's terms. You may disconnect integrations, and Sauti may suspend an integration when credentials expire or its use creates security, legal, or operational risk."]},
{id:"acceptable",title:"Acceptable use",bullets:["Do not violate law, intellectual-property, privacy, publicity, consumer-protection, telecommunications, sanctions, or export-control requirements.","Do not upload malware, bypass security, disrupt the platform, scrape it at scale, reverse engineer protected components, or access another tenant's data.","Do not use generated content as the sole basis for decisions affecting healthcare, employment, credit, housing, insurance, legal rights, or essential services.","Do not collect full payment-card credentials, account passwords, government identifiers, or special-category data unless the feature, law, safeguards, and notice clearly support it.","Payment and other consequential tools must preserve confirmation steps; you may not configure an agent to bypass them."]},
{id:"fees",title:"Plans, usage, and payment",paragraphs:["Paid features are billed according to the plan and pricing presented at purchase or in an order. Usage may include call minutes, phone numbers, messages, storage, provider charges, or integration operations. Unless stated otherwise, fees are exclusive of taxes and non-refundable except where law requires. We may limit or suspend usage when plan limits, overdue amounts, fraud, or material operational risk applies."]},
{id:"ownership",title:"Intellectual property and feedback",paragraphs:["Sauti and its licensors own the platform, software, design, documentation, and related technology. These Terms grant a limited, revocable, non-exclusive, non-transferable right to use the service during your subscription. You retain rights in your business content. If you provide feedback, you permit Sauti to use it without restriction or obligation, without identifying confidential customer information."]},
{id:"availability",title:"Availability, changes, and third parties",paragraphs:["We work to provide a reliable service but do not guarantee uninterrupted or error-free operation. Telephony carriers, internet connectivity, model providers, Google APIs, calendars, CRMs, and other third parties may affect latency, accuracy, delivery, or availability. We may maintain, modify, discontinue, or replace features and will provide reasonable notice when a material change significantly affects active paid use where practicable."]},
{id:"termination",title:"Suspension and termination",paragraphs:["You may stop using Sauti at any time. We may restrict or terminate access for material breach, unlawful or harmful activity, security risk, non-payment, provider requirement, or where continued service is impracticable. Where appropriate, we will provide notice and an opportunity to remedy. On termination, access ends and data is handled under the Privacy Policy and applicable retention obligations."]},
{id:"liability",title:"Disclaimers and liability",paragraphs:["To the extent permitted by law, Sauti is provided on an 'as available' basis without implied warranties of merchantability, fitness for a particular purpose, or non-infringement. You are responsible for reviewing AI output and maintaining appropriate business continuity.","To the extent permitted by law, Sauti will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, lost profits, revenue, goodwill, or data. Sauti's aggregate liability arising from the service will not exceed the fees paid by you during the twelve months preceding the event giving rise to the claim. Nothing excludes liability that cannot legally be excluded."]},
{id:"general",title:"Changes, general terms, and contact",paragraphs:["We may update these Terms to reflect service, legal, or security changes. Material updates will be communicated appropriately and take effect on the stated date. Continued use after that date constitutes acceptance where permitted by law. If part of these Terms is unenforceable, the remainder continues. Failure to enforce a provision is not a waiver. Questions can be sent to support@sauti.uk."]}
];
export default function TermsPage(){return <LegalDocument eyebrow="Legal" title="Terms built for clear collaboration" summary="The practical rules for operating AI voice agents, connected workflows, and customer conversations responsibly on Sauti." effectiveDate="12 July 2026" icon={ScrollText} highlights={["You control agent configuration and connected services","AI outputs require appropriate human review","Consent and communication compliance remain essential"]} sections={sections}/>}
